package pojo;
// Generated 14 Oct, 2019 12:44:52 AM by Hibernate Tools 5.2.3.Final

/**
 * AvailableProducts generated by hbm2java
 */
public class AvailableProducts implements java.io.Serializable {

	private AvailableProductsId id;
	private Products products;

	public AvailableProducts() {
	}

	public AvailableProducts(AvailableProductsId id, Products products) {
		this.id = id;
		this.products = products;
	}

	public AvailableProductsId getId() {
		return this.id;
	}

	public void setId(AvailableProductsId id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

}
