package pojo;
// Generated 14 Oct, 2019 12:44:52 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * CustomerInfo generated by hbm2java
 */
public class CustomerInfo implements java.io.Serializable {

	private Integer customerId;
	private String customerName;
	private String customerContact;
	private String customerEmail;
	private String customerAddress;
	private String city;
	private String state;
	private int pincode;
	private String password;
	private Set reservedProductses = new HashSet(0);

	public CustomerInfo() {
	}

	public CustomerInfo(String customerName, String customerContact, String customerEmail, String city, String state,
			int pincode, String password) {
		this.customerName = customerName;
		this.customerContact = customerContact;
		this.customerEmail = customerEmail;
		this.city = city;
		this.state = state;
		this.pincode = pincode;
		this.password = password;
	}

	public CustomerInfo(String customerName, String customerContact, String customerEmail, String customerAddress,
			String city, String state, int pincode, String password, Set reservedProductses) {
		this.customerName = customerName;
		this.customerContact = customerContact;
		this.customerEmail = customerEmail;
		this.customerAddress = customerAddress;
		this.city = city;
		this.state = state;
		this.pincode = pincode;
		this.password = password;
		this.reservedProductses = reservedProductses;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getCustomerContact() {
		return this.customerContact;
	}

	public void setCustomerContact(String customerContact) {
		this.customerContact = customerContact;
	}

	public String getCustomerEmail() {
		return this.customerEmail;
	}

	public void setCustomerEmail(String customerEmail) {
		this.customerEmail = customerEmail;
	}

	public String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public int getPincode() {
		return this.pincode;
	}

	public void setPincode(int pincode) {
		this.pincode = pincode;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getReservedProductses() {
		return this.reservedProductses;
	}

	public void setReservedProductses(Set reservedProductses) {
		this.reservedProductses = reservedProductses;
	}

}
