package pojo;
// Generated 14 Oct, 2019 12:44:52 AM by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Products generated by hbm2java
 */
public class Products implements java.io.Serializable {

	private Integer productId;
	private PublicityDetails publicityDetails;
	private String productType;
	private String productLocation;
	private Double longitude;
	private Double latitude;
	private Double sizex;
	private Double sizey;
	private String productStatus;
	private int productLevelHeight;
	private String productImage;
	private int productPrice;
	private Set availableProductses = new HashSet(0);
	private Set reservedProductses = new HashSet(0);

	public Products() {
	}

	public Products(PublicityDetails publicityDetails, String productType, String productLocation, String productStatus,
			int productLevelHeight, int productPrice) {
		this.publicityDetails = publicityDetails;
		this.productType = productType;
		this.productLocation = productLocation;
		this.productStatus = productStatus;
		this.productLevelHeight = productLevelHeight;
		this.productPrice = productPrice;
	}

	public Products(PublicityDetails publicityDetails, String productType, String productLocation, Double longitude,
			Double latitude, Double sizex, Double sizey, String productStatus, int productLevelHeight,
			String productImage, int productPrice, Set availableProductses, Set reservedProductses) {
		this.publicityDetails = publicityDetails;
		this.productType = productType;
		this.productLocation = productLocation;
		this.longitude = longitude;
		this.latitude = latitude;
		this.sizex = sizex;
		this.sizey = sizey;
		this.productStatus = productStatus;
		this.productLevelHeight = productLevelHeight;
		this.productImage = productImage;
		this.productPrice = productPrice;
		this.availableProductses = availableProductses;
		this.reservedProductses = reservedProductses;
	}

	public Integer getProductId() {
		return this.productId;
	}

	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	public PublicityDetails getPublicityDetails() {
		return this.publicityDetails;
	}

	public void setPublicityDetails(PublicityDetails publicityDetails) {
		this.publicityDetails = publicityDetails;
	}

	public String getProductType() {
		return this.productType;
	}

	public void setProductType(String productType) {
		this.productType = productType;
	}

	public String getProductLocation() {
		return this.productLocation;
	}

	public void setProductLocation(String productLocation) {
		this.productLocation = productLocation;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getSizex() {
		return this.sizex;
	}

	public void setSizex(Double sizex) {
		this.sizex = sizex;
	}

	public Double getSizey() {
		return this.sizey;
	}

	public void setSizey(Double sizey) {
		this.sizey = sizey;
	}

	public String getProductStatus() {
		return this.productStatus;
	}

	public void setProductStatus(String productStatus) {
		this.productStatus = productStatus;
	}

	public int getProductLevelHeight() {
		return this.productLevelHeight;
	}

	public void setProductLevelHeight(int productLevelHeight) {
		this.productLevelHeight = productLevelHeight;
	}

	public String getProductImage() {
		return this.productImage;
	}

	public void setProductImage(String productImage) {
		this.productImage = productImage;
	}

	public int getProductPrice() {
		return this.productPrice;
	}

	public void setProductPrice(int productPrice) {
		this.productPrice = productPrice;
	}

	public Set getAvailableProductses() {
		return this.availableProductses;
	}

	public void setAvailableProductses(Set availableProductses) {
		this.availableProductses = availableProductses;
	}

	public Set getReservedProductses() {
		return this.reservedProductses;
	}

	public void setReservedProductses(Set reservedProductses) {
		this.reservedProductses = reservedProductses;
	}

}
