package pojo;
// Generated 14 Oct, 2019 12:44:52 AM by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * PublicityFeedbacksId generated by hbm2java
 */
public class PublicityFeedbacksId implements java.io.Serializable {

	private int productId;
	private int publicityId;
	private String feedback;
	private int rating;
	private Date date;
	private String additionalImage;

	public PublicityFeedbacksId() {
	}

	public PublicityFeedbacksId(int productId, int publicityId, String feedback, int rating, Date date) {
		this.productId = productId;
		this.publicityId = publicityId;
		this.feedback = feedback;
		this.rating = rating;
		this.date = date;
	}

	public PublicityFeedbacksId(int productId, int publicityId, String feedback, int rating, Date date,
			String additionalImage) {
		this.productId = productId;
		this.publicityId = publicityId;
		this.feedback = feedback;
		this.rating = rating;
		this.date = date;
		this.additionalImage = additionalImage;
	}

	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public int getPublicityId() {
		return this.publicityId;
	}

	public void setPublicityId(int publicityId) {
		this.publicityId = publicityId;
	}

	public String getFeedback() {
		return this.feedback;
	}

	public void setFeedback(String feedback) {
		this.feedback = feedback;
	}

	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getAdditionalImage() {
		return this.additionalImage;
	}

	public void setAdditionalImage(String additionalImage) {
		this.additionalImage = additionalImage;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PublicityFeedbacksId))
			return false;
		PublicityFeedbacksId castOther = (PublicityFeedbacksId) other;

		return (this.getProductId() == castOther.getProductId())
				&& (this.getPublicityId() == castOther.getPublicityId())
				&& ((this.getFeedback() == castOther.getFeedback()) || (this.getFeedback() != null
						&& castOther.getFeedback() != null && this.getFeedback().equals(castOther.getFeedback())))
				&& (this.getRating() == castOther.getRating())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& ((this.getAdditionalImage() == castOther.getAdditionalImage())
						|| (this.getAdditionalImage() != null && castOther.getAdditionalImage() != null
								&& this.getAdditionalImage().equals(castOther.getAdditionalImage())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProductId();
		result = 37 * result + this.getPublicityId();
		result = 37 * result + (getFeedback() == null ? 0 : this.getFeedback().hashCode());
		result = 37 * result + this.getRating();
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getAdditionalImage() == null ? 0 : this.getAdditionalImage().hashCode());
		return result;
	}

}
