package pojo;
// Generated 14 Oct, 2019 12:44:52 AM by Hibernate Tools 5.2.3.Final

/**
 * PublicityFeedbacks generated by hbm2java
 */
public class PublicityFeedbacks implements java.io.Serializable {

	private PublicityFeedbacksId id;

	public PublicityFeedbacks() {
	}

	public PublicityFeedbacks(PublicityFeedbacksId id) {
		this.id = id;
	}

	public PublicityFeedbacksId getId() {
		return this.id;
	}

	public void setId(PublicityFeedbacksId id) {
		this.id = id;
	}

}
