package pojo;
// Generated 14 Oct, 2019 12:44:52 AM by Hibernate Tools 5.2.3.Final

/**
 * ReservedProducts generated by hbm2java
 */
public class ReservedProducts implements java.io.Serializable {

	private ReservedProductsId id;
	private CustomerInfo customerInfo;
	private Products products;

	public ReservedProducts() {
	}

	public ReservedProducts(ReservedProductsId id, CustomerInfo customerInfo, Products products) {
		this.id = id;
		this.customerInfo = customerInfo;
		this.products = products;
	}

	public ReservedProductsId getId() {
		return this.id;
	}

	public void setId(ReservedProductsId id) {
		this.id = id;
	}

	public CustomerInfo getCustomerInfo() {
		return this.customerInfo;
	}

	public void setCustomerInfo(CustomerInfo customerInfo) {
		this.customerInfo = customerInfo;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

}
